SIR / MADAM,
PLEASE SAY US HOW CAN WE KNOW ABOUT THE PREVIOUS PROJECT 
I REALLY WANNA KNOW HOW DID I DO WITH MY FRIST PROJECT AND IF HAVE DONE ANY MISTAKES THEN I REALLY  WANNA LEARN HOW TO CORRECT THEM 
